package com.tourism.strategy.tourism_strategy.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.tourism.strategy.tourism_strategy.model.Consume;

import com.tourism.strategy.tourism_strategy.greendao.ConsumeDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig consumeDaoConfig;

    private final ConsumeDao consumeDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        consumeDaoConfig = daoConfigMap.get(ConsumeDao.class).clone();
        consumeDaoConfig.initIdentityScope(type);

        consumeDao = new ConsumeDao(consumeDaoConfig, this);

        registerDao(Consume.class, consumeDao);
    }
    
    public void clear() {
        consumeDaoConfig.clearIdentityScope();
    }

    public ConsumeDao getConsumeDao() {
        return consumeDao;
    }

}
